### ISSUE TITLE
Private link access support request

### ISSUE THREAD

**Issue by lucashby** [Azure-Terraform/terraform-azurerm-storage-account#43]
Could you please add support to the module for [private_link_access](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#private_link_access)?

**Comment by lucashby** [comment]
I went ahead and sent an email to coreservices@lexisnexisrisk.com after testing myself to see if private_link_access is what is required and it works as I need it to since service endpoints are not available for Synapse.  This was inline with what @dutsmiller had requested I do.

**Comment by dutsmiller** [comment]
The issue here is that the storage account module manages the network access as well.  Since the synapse workspace requires a dlg2 filesystem, which requires a storage account, this creates a dependency cycle.  The best advice I could give would be to use the azurerm resources directly (rather than this module) and check your config against the infosec guidelines for network security.
